name: Size

on: [pull_request]

jobs:
    size:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20.11.1
            - name: Use node_modules cache
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: yarn-node-20-lock-${{ hashFiles('yarn.lock') }}
                  restore-keys: |
                      yarn-node-20-lock-
            - run: yarn install --frozen-lockfile
            - uses: andresz1/size-limit-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  skip_step: install
